### ISSUE TITLE
zh_CN#Hans locale is invalid

### ISSUE THREAD

**Issue by purefun** [localazy/strapi-plugin#1]
May `zh_CN#Hans` is not a valid language code. Strapi only accepts `zh-Hans-CN` I think.

![CleanShot 2022-07-04 at 18 01 21](https://user-images.githubusercontent.com/3140656/177132107-5c32bcc2-11c4-4eee-a40c-3e662fa768d7.png)

**Comment by honzabilek4** [comment]
Thanks, @purefun!
@david-vaclavek could you please take a look at what's happening here?

**Comment by david-vaclavek** [comment]
@purefun also big thanks for reporting. Took a look at that, fixed the issue, it's currently under review.

We'll let you know as soon as the fix will be in production branch.

**Comment by purefun** [comment]
@david-vaclavek Thanks a lot. Btw, After I introduced Localazy to my teammates, they loved it. We use Localazy for our web, flutter, python, and golang backends, and Qt projects.

**Comment by david-vaclavek** [comment]
@purefun Love to hear that you're enjoying using Localazy! 🙏🏼
