### ISSUE TITLE
[Feature Request] Enable custom or option to change ID used on key generation

### ISSUE THREAD

**Issue by gfsd3v** [localazy/strapi-plugin#11]
Hey folks,

First of all thx for the awesome plugin/work, it helped a lot setting locale on our project.

One thing that it would make easier to work with is a better way to find the key being used on Localazy based on information available on Strapi. If I understood correctly the Localazy key is generated based on the index of the available options for that entity, eg:

![image](https://user-images.githubusercontent.com/36668882/196225102-8cf04efd-afd5-48d7-a75d-e0b87458aff9.png)

In our case sometimes the content team want to change some wording for a specific key due to SEO, with the current implementation the only way to find the key that is being used is checking the string that is being translated, if the string is the same it becomes really hard to make the relation of which key is being used.

A possible solution would be to instead of using indexes is maybe using the ID of the entry itself? This way we can easily check the ID of the entry on Strapi and check the same ID for that entity on Localazy.

What you guys think? Also, do u have any suggestions on a quick fix to solve the above problem?

Thanks for the help (:

**Comment by david-vaclavek** [comment]
Hello @gfsd3v.
Thank you for the feedback, we're really happy that you like the plugin!

Exactly, as you've discovered on your own, it already works with the IDs of the entries.

Currently, we're finishing a support for Dynamic Zones. It will be released in the upcoming weeks, so stay tuned for the update!

We'll be glad for any feedback as we're eager to improve the plugin for users' needs.
