### ISSUE TITLE
Simplified Chinese zh#Hans Does not get Downloaded to Strapi

### ISSUE THREAD

**Issue by kopoev** [localazy/strapi-plugin#13]
Uploaded English (en) to Localazy via Strapi Admin Panel.
Made test translations to other 3 languages via Localazy website.
When I click "Download to Strapi" via "Strapi Admin Panel" all additional 3 languages are being installed, along with  "Simplified Chinese (zh-Hans)", confirmed in Admin->Settings->Internationalization.
Two of translation language content get populated.
"Simplified Chinese zh#Hans" is missing, even "Download completed: Content successfully imported to Strapi." status was received. The other two languages get updated correctly.

**Comment by david-vaclavek** [comment]
Hello @kopoev. Thank you for reporting the issue.

We fixed the bug in the latest release [v0.1.11-rc.2](https://github.com/localazy/strapi-plugin/tree/v0.1.11-rc.2).
Everything should work fine now!

**Comment by kopoev** [comment]
awesome, @david-vaclavek, thanks
will test when released
