### ISSUE TITLE
No translatable required fields

### ISSUE THREAD

**Issue by gfsd3v** [localazy/strapi-plugin#15]
I'm running into a problem and tbh  idk how it should be handled on the plugin side.

The problem is that when u have a required field that it doesn't need to be translated the plugin fails to create the entry on Strapi.

Here's a example:

I've a `Shared.Seo` component that receives a `metaTitle` and `metaDescription` and I use it on certain collection types that are pages that I need to create.
![image](https://user-images.githubusercontent.com/36668882/198119088-aa3aa51f-1147-4a34-b1cd-5c3022ebb912.png)

I don't want my title to be translated, only the description.
![image](https://user-images.githubusercontent.com/36668882/198119788-7782d411-a6fb-414f-ba33-2d3e586df0e5.png)

When I try to download the translations from Localazy using the plugin I get the following validation errors:
![image](https://user-images.githubusercontent.com/36668882/198120236-9fb50f12-e8d7-486b-9b88-ac7e252461a8.png)

I would like to keep the `metaTitle` field required without translations, is there a way to do that? Currently I removed the required in order to have translations in place.

PS: If you have more then one required field the error message is not so informative, I used this to be able to debug it better: 
https://github.com/strapi/strapi/issues/12026#issuecomment-1001178952

**Comment by david-vaclavek** [comment]
Hello @gfsd3v, thank you for reporting the issue.

The current solution is the one you're decided to make (remove the required flag).
We're already aware of this and set a priority to it. We'll be working on the fix during the next week.

Will let you know the updates!

**Comment by honzabilek4** [comment]
Hello, 
This has been resolved. It should now work as expected. Please try it out and let us know.

**Comment by gfsd3v** [comment]
@honzabilek4  Sorry for the late reply, its working flawless.

Kudos for the update on this and on also automatically filling the entries based on the source language content, I had wrote a script to do this using Strapi API, really good to have it on the plugin it self, it saved me and the team responsible for the content a lot of time :+1:
