### ISSUE TITLE
Cannot create translated content with relations that can't be fulfilled

### ISSUE THREAD

**Issue by Grouviere** [localazy/strapi-plugin#23]
Hi Guys,

so, here is the issue : 
Content type A contains an optional relation One to One to Content type B
Content type A also contains an optional One to Many to Content type A

If I create a type A content in main language (EN), with relations with EN content (types A and B) and then want to translate this content into french (FR), if the related content doesn't already exist in FR, the download operation from localazy crashes as it fails to create the FR instance of the content. Seems that it tries to link original related contents in EN with the newly created FR one and crashes doing so.

It works if : 
- the FR versions of the related content A and B already exist and are published
- the FR content of the type A content I'm trying to translate is already created, even if full blank, then the download operation fill all the fields (except the relations) and succeed

I think that failing into linking content from other languages should fail the creation operation of the newly translated content, moreover if this relation is an optional field.

In our own example, content A is a product, with relations with related products. So every product is linked with other products, meaning there is so way of translating (and creating other languages versions) in a right order. It should just create every product omitting the relations as there's no other choice, and then we'll have to contribute the relations on translated content ourselves.

Thanks !

**Comment by david-vaclavek** [comment]
Hello Guillaume,

I'd like to inform you that we've recently rolled out a new version, packed with numerous fixes for both the upload and download processes. We believe there's a strong possibility that this release could address the specific issue you described.

You can find the updated plugin version [here](https://www.npmjs.com/package/@localazy/strapi-plugin/v/0.1.16). If you're inclined to give it a try, please let us know. We greatly value your feedback.

For the time being, I'll be closing this ticket. However, if you happen to encounter any persisting problems, don't hesitate to reach out, and I'll promptly reopen the issue.

Thank you.
