### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'crypto' in 'path/node_modules/@localazy/strapi-plugin/server/middlewares'

### ISSUE THREAD

**Issue by NikitK-deriv** [localazy/strapi-plugin#30]
I'm using "@localazy/strapi-plugin": "^0.1.13-rc.6" for @strapi/strapi
After update from version strapi version 4.6.0 to 4.7.1 found that localazy plugin can't resolve 'crypto' module in build time. In package.json isn't exist

It can be resolved by adding in package.json this code:
```
"browser": {
    "crypto": false
  }
```
Also we can install crypto-browserify and add this code:
`"crypto": require.resolve("crypto-browserify")`

Main idea is to use cryptography as far as I realize. Could you please resolve this issue? 
<img width="1668" alt="Screenshot 2023-03-07 at 13 38 55" src="https://user-images.githubusercontent.com/103182473/223401015-d0452ec4-6987-49e0-ac6c-56adf230dd31.png">

<img width="810" alt="Screenshot 2023-03-07 at 13 40 10" src="https://user-images.githubusercontent.com/103182473/223401029-42004da8-ec55-4b92-8a67-dd4d072e33f1.png">

<img width="1185" alt="Screenshot 2023-03-07 at 13 40 59" src="https://user-images.githubusercontent.com/103182473/223401045-3ab6911f-b113-481a-855f-2367770840f4.png">

**Comment by david-vaclavek** [comment]
Hello, thanks for reporting the issue.

Haven't come across the issue during the development.
I was able to replicate it on a clean project.

Hot fixed in 71a957163f68a54281a3a4b96ff50dedc8cbeb15.

Available as a part of [v0.1.13-rc.7](https://www.npmjs.com/package/@localazy/strapi-plugin/v/0.1.13-rc.7).
