### ISSUE TITLE
Unusable with Strapi 4.20.0 - Stuck on loading

### ISSUE THREAD

**Issue by gassenta** [localazy/strapi-plugin#47]
I've recently tried to upgrade Strapi to version 4.20.0 from 4.12.5, I also updated the plugin from 0.1.14 to 0.2.3, but as for title on each page of the Localazy plugin the spinner is never going away, nor any failing http request or log in the browser/server console. 

<img width="1800" alt="image" src="https://github.com/localazy/strapi-plugin/assets/46087431/baa014a7-40f9-486d-bc0f-047657f14c99">

# Steps to reproduce:
1. create a new strapi 4.20.0 project using `yarn create strapi-app my-project`
2. install Localazy plugin using `yarn add @localazy/strapi-plugin@latest`
3. run `npx @localazy/strapi-plugin`
4. add custom `src/admin/webpack.config.js` with contents below

```JavaScript
module.exports = (config, webpack) => {
  // Note: we provide webpack above so you should not `require` it
  // Perform customizations to webpack config
  // Important: return the modified config

  return {
    ...config,
    resolve: {
      ...config.resolve,
      fallback: {
        ...config.resolve.fallback,
        crypto: false,
        http: false,
        fs: false,
        zlib: false,
        https: false,
        stream: false,
        path: false,
        timers: false,
        tls: false,
        net: false,
        url: false,
        querystring: false,
      },
    }
  };
};
```

**Comment by gassenta** [comment]
Tried to upgrade to plugin version 0.2.4 and strapi 4.20.5, still no luck. Any hint?

**Comment by david-vaclavek** [comment]
Hello @gassenta.

I just tried with a clean Strapi project v4.20.5 and @localazy/strapi-plugin v0.2.4 and it runs smoothly.

**Comment by gassenta** [comment]
Thanks @david-vaclavek, I did attempted before installing localazy on a fresh project but I had the same issue. 

Issue solved: https://github.com/localazy/strapi-plugin/commit/5f55f1bfe406b1040c78d00bca5feafe0d23c45b

Suggestion for improvement: add proper console error pointing to the missing param in the .env, currently the effect is the one described in this issue. 

<img width="656" alt="image" src="https://github.com/localazy/strapi-plugin/assets/46087431/3f8cf240-ae29-4de9-ba0c-520f253cc494">


<img width="423" alt="image" src="https://github.com/localazy/strapi-plugin/assets/46087431/e8837141-e14c-48e1-a8e0-26a200d1f7b5">
