### ISSUE TITLE
Endpoints for end users

### ISSUE THREAD

**Issue by multipliedtwice** [localazy/strapi-plugin#6]
Hello, thank you for a great plugin. I have a question - the content on my Strapi project is created by end users. Is there any way to let them upload their own content for localization by themselves? That would probably open some referral opportunities as well.

**Comment by honzabilek4** [comment]
Hi @thousandsofraccoons, 
As you probably noticed, we've released the plugin quite recently, and we welcome feedback and suggestions for improvements. 
Could you please describe what your whole Strapi workflow looks like and how does the plugin fit there?
We can also discuss this on call if you wish. Just shoot me a message at `jan[at]localazy.com`

**Comment by david-vaclavek** [comment]
Closing this one for inactivity.
