### ISSUE TITLE
Localization for dynamic zones

### ISSUE THREAD

**Issue by Niles-XIII** [localazy/strapi-plugin#8]
**Bug report**
---
**Required System information**
- Node.js version: v14.17.6
- NPM version: 6.14.15
- Strapi version: 4.3.8
- Localazy strapi version: 0.1.10

**Describe the bug**
Dynamic zones are not detected as localizable fields in Content Transfer Setup even when their possible components have text fields in them

**Steps to reproduce the behavior**
1. Create a couple of different components with  _Text_-typed fields in Strapi
2. Create a _Collection Type_ with a dynamic zone and each component created on step 1 as the dynamic zone components
3. Go to "Settings">"Content Transfer Setup" and expand the type created on step 2

**Expected behavior**
Be able to select text fields in dynamic zone components to upload them to Localazy.

**Aditional context**
We are evaluating the adoption of Localazy and not being able to properly set-up localization for dynamic zones is a deal breaker for us.

**Comment by david-vaclavek** [comment]
Hello! We've collected this request from a couple of users already and added the feature to our pipeline.

We will let you know in case of the updates!

By the way, we'll be glad for any other feedback regarding the plugin as we're eager to improve it to our users needs!

**Comment by david-vaclavek** [comment]
Hello, @RomanBON, @Niles-XIII.

Our latest release candidate [v0.1.11-rc.2](https://github.com/localazy/strapi-plugin/tree/v0.1.11-rc.2) adds a support for Dynamic Zones.

We'll be glad for any feedback regarding the feature.
