### ISSUE TITLE
menu item not showing after install

### ISSUE THREAD

**Issue by ramiavital** [localazy/strapi-plugin#9]
i installed on my local version 4.3.9
i see it in the list of plugins under general 
but i dont have the flag menu item 

any idea

**Comment by david-vaclavek** [comment]
Hello, have you installed the plugin via npm? Do you have the latest version of plugin?

Also I'd recommend to have the latest version of Strapi installed.

I can't reproduce the issue right now, everything works as desired. Do you have some specific Strapi configuration?

Lastly, I'd try to install the plugin on the clean Strapi instance and see whether it works on your machine.

**Comment by ramiavital** [comment]
Hi, yes i installed with npm
and latest version 
should i add it in the plugins.js ?
because it doesnt exist there

**Comment by david-vaclavek** [comment]
That's weird, all of this should happen automatically via Strapi Core.

One more thing that comes to my mind: Did you run the `build` command after installing the plugin? Admin needs to be re-built after that.

**Comment by ramiavital** [comment]
yep the build did the magic :) 
thanks

**Comment by david-vaclavek** [comment]
Happy to help!

We'll be glad for any feedback regarding the plugin as we're eager to improve to our users needs!

Currently working on an update that allows you to selectively assign the "Strapi default language values fallback" for any of the untranslated values (think images, boolean, numbers, relations, ...).
